#_*_ coding:utf-8 _*_
# Django settings for SmartHome project.
# Generated by 'django-admin startproject' using Django 1.8.17.
# 进行项目开发时，每新建一个APP必须往INSTALLED_APPS里面添加，否则无法识别。
# 该文件也定义了项目模板文件位置，具体APP模板，可存放于./appname/templates/home/
# 数据库配置默认为Django默认的数据库，在实际使用中可配置为MySQL等性能较高的数据库。

import os
from django.conf import global_settings

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# 为保证项目的可移植性，使用Python标准库获取项目的绝对路径，开发时只需要在此基础
# 上以相对路径进行开发便可。
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2vcbou^s8#(7n95aagk^l&h@f-^7arol$blnw208$9=24)p*ue'

# SECURITY WARNING: don't run with debug turned on in production!
# 项目开发时为调试的方便，设置为True，但是项目发布时应调整为False
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# 新建的APP要在此添加，使项目能够识别到。
# 使用单引号将其包含，每个APP添加后记得后面有一个逗号。
INSTALLED_APPS = (
    'bootstrap_admin', # 后台美化插件bootstrap_admin 必须放在django.contrib.admin前面。
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'DjangoUeditor',
)

# 此为使用后台界面优化插件所定义的部分。
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
            # insert your TEMPLATE_DIRS here
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                # list if you haven't customized them:
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request'
            ]
        },
    },
]

BOOTSTRAP_ADMIN_SIDEBAR_MENU = True

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'SmartHome.urls'

WSGI_APPLICATION = 'SmartHome.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# 在此配置数据库，以下为使用默认的数据库，在实际的使用中可将其配置成为MySQL。
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 公共的 static 文件可以放这里，这里面的文件夹不能包含 STATIC_ROOT
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "common_static"),
)

# upload folder
# 存放图片，视频，文件等资源的地方，位于该项目下的media文件。
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
